version: '3.7'

services:
  tf_serving:
    build: ./tf_serving
    expose:
      - 8501
    environment:
      - MODEL_NAME=secret_model
      - MODEL_BASE_PATH=/models/vault_models 
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    expose:
      - 8000
    environment:
      - FLAG=testflag
      - MODEL=secret_model
    depends_on:
      - tf_serving
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
  
